Models/ErrorViewModel.cs
using System;

namespace SymTom.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Symptom.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SymTom.Models
{
    public class Symptom
    {
       public int ID { get;  set; }

        public string Name { get; set; }
        public int Severity { get; set; }

        public string Location { get; set; }

        public string Date { get; set; }

        


       

    }
}

ViewModels/AddSymptomViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SymTom.ViewModels
{
    public class AddSymptomViewModel 
    { 


        public int ID { get; set; }

        [Required]
        [Display(Name = "Symptom")]
        public string Name { get; set; }


        [Required]
        public string Location { get; set; }


        [Required(ErrorMessage = " Give your symptom a severity")]
        public int Severity { get; set; }

        [Display(Name = "Date Noticed")]
        [Required(ErrorMessage = "Please enter a start date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public string Date { get; set; }



        }
}

Controllers/CreatePdfController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using SymTom.Models;
using SymTom.Data;
using Grpc.Core;
using static iTextSharp.text.Font;

namespace SymTom.Controllers
{
    public class CreatePdfController : Controller
    {
        private readonly SymptomDbContext context;

        public CreatePdfController(SymptomDbContext dbContext)
        {
            context = dbContext;
        }

        [HttpPost]
        [ActionName("Index")]
        public ActionResult Index_Post()
        {
            List<Symptom> symptoms = context.Symptoms.ToList();
            Document pdfDoc = new Document(PageSize.A4, 25, 25, 25, 15);
            PdfWriter pdfWriter = PdfWriter.GetInstance(pdfDoc, Response.Body);
            pdfDoc.Open();


            

            PdfPTable symptom = new PdfPTable(4); 
            {
                Font hope = new Font(FontFamily.COURIER, 16, Font.BOLD);
                

                Paragraph loc = new Paragraph("Location", hope);
                Paragraph sym = new Paragraph("Symptom", hope);
                Paragraph dat = new Paragraph("Date", hope);
                Paragraph sev = new Paragraph("Severity", hope);

                symptom.AddCell(loc); //col 1 row 1
                
                symptom.AddCell(sym); //col 2 row 1
                symptom.AddCell(dat); //col 1 row 2
                symptom.AddCell(sev); //col 2 row 2
                
                foreach (var item in symptoms)
                {
                    symptom.AddCell(item.Location);
                    symptom.AddCell(item.Name);                    
                    symptom.AddCell(item.Date);
                    symptom.AddCell(item.Severity.ToString());

                }

                symptom.HorizontalAlignment = Element.ALIGN_CENTER;

            }//declare new table
             //col 1 row 3
            string url = "https://doctorfreedompodcast.podbean.com/mf/web/4pmf3k/2-doctors-x-ray.jpg";
            Image img = Image.GetInstance(url);
            img.ScaleToFit(800f, 800f);
            img.HasBorders();
            
            img.ScaleAbsolute(500f, 500f);
            img.Alignment = Element.ALIGN_CENTER;


            Font font = new Font(FontFamily.HELVETICA, 20, Font.BOLD);
            Font stew = new Font(FontFamily.HELVETICA, 16, Font.BOLD, BaseColor.RED);


            Paragraph header = new Paragraph("List of Symptoms",font);
            header.Alignment=Element.ALIGN_CENTER;
            header.SetLeading(18,0);

            Paragraph sent = new Paragraph("Remember to speak with your physician about these symptoms at your next appointment.", stew);
            sent.Alignment = Element.ALIGN_CENTER;


            pdfDoc.Add(header);
            pdfDoc.Add(Chunk.NEWLINE);
            pdfDoc.Add(symptom);
            pdfDoc.Add(Chunk.NEWLINE);
            pdfDoc.Add(sent);
            pdfDoc.Add(img);
            pdfDoc.Close();
            
            

            return View();
        }
        
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SymTom.Models;

namespace SymTom.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

       
    }
}

Controllers/SymptomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.PortableExecutable;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SymTom.Data;
using SymTom.Models;
using SymTom.ViewModels;

namespace SymTom.Controllers
{
    public class SymptomController : Controller
    {
        private readonly SymptomDbContext context;

        public SymptomController(SymptomDbContext dbContext)
        {
            context = dbContext;
        }

        public IActionResult Index()
        {

            /*var allSymptoms = context.Symptoms.ToList();*/
            return View();
        }

        

        public IActionResult Add()
        {
            AddSymptomViewModel addSymptomViewModel = new AddSymptomViewModel();
            return View(addSymptomViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddSymptomViewModel addSymptomViewModel)
        {
            
                // Add the new symptom to my existing symptoms
                Symptom newSymptom = new Symptom
                {
                    Name = addSymptomViewModel.Name,
                    Date = addSymptomViewModel.Date,
                    Location = addSymptomViewModel.Location,
                    Severity= addSymptomViewModel.Severity,
                };

                context.Symptoms.Add(newSymptom);
                context.SaveChanges();

                return Redirect("/Symptom/List");
            

            
        }
    
        


        public IActionResult List()
        {
            IList<Symptom> symptoms = context.Symptoms.ToList();
           return View(symptoms);
        }
         public IActionResult Remove()
        {
            IList<Symptom> symptoms = context.Symptoms.ToList();
            return View(symptoms);
        }

        [HttpPost]
        public IActionResult Remove(int[] symptomIds)
        {
            foreach (int symptomId in symptomIds)
            {
                Symptom theSymptom = context.Symptoms.Single(c => c.ID == symptomId);
                context.Symptoms.Remove(theSymptom);
            }

            context.SaveChanges();
           

            return Redirect("/Symptom/List");
        }

        
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-lg-center ">
    <h1 class="display-4">Welcome to Sym Tom</h1>
</div>
<div class="container">
    <div class="row">
        <div class="col">

            <div class="card shadow">
                <div class="card-header">I am here to keep track of what ails you!</div>
                <div class="card-body">Click on the heart to get started</div>
            </div>

        </div>
        <div class="col ">
            <div class="rounded ">
                <a href="/Symptom/Add">
                    <img  style="border:1px solid black;" src="https://lh6.googleusercontent.com/proxy/D2ptDGTOio2m9c0-fjUc4Ay9Ev0h5RBAA_UWIvlC1S70sCw_1xC6fCfh3MVRme26JdAsIMAOj0_D87Y-k_V5ikKpf_5Fb9KxQmX_QFhO1dljrWigVD1vCXn9v_7sEx4ImRN1Ys05IpEBETeFj5arFAyDHbcFg5FPs7qSdt0e9cWguCmZkYgE5l0IfEGrjR2N6w" width="400" height="300">

                </a>

            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - SymTom</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>

    <body style="background-image: url('https://media.istockphoto.com/photos/group-of-doctors-in-a-hurry-down-the-hospital-hallway-picture-id856544984?k=6&m=856544984&s=612x612&w=0&h=A18T00Xv9OtjhdD_ZZK7eaKTRUTvcJDwIOv48q3uUbA='); background-attachment: fixed;
  background-size: cover; background-repeat: no-repeat">

        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container">
                    <a class="navbar-brand shadow" href="/">Sym Tom</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Menu
                                </a>
                                <!-- Here's the magic. Add the .animate and .slide-in classes to your .dropdown-menu and you're all set! -->
                                <div class="dropdown-menu dropdown-menu-right animate slideIn" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item " href="/Symptom/Add">Add a Symptom</a>
                                    <a class="dropdown-item " href="/Symptom/Remove">Remove a Symptom</a>
                                    <a class="dropdown-item" href="/Symptom/List">List of Symptoms</a>

                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

        </header>
        <div class="container">
            <div class="card border-secondary shadow my-5">
                <div class="card-body p-5">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>

        <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
            <div class="container text-center">
                &copy; 2020 - SymTom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)

    </body>

</html>

Views/Symptom/Add.cshtml
@model SymTom.ViewModels.AddSymptomViewModel



<div class="text-lg-center">
    <h1 class="display-4">Select a Body Part</</h1>
</div>
<div class="container float-right">
    <div class="row">
        <div class="col ">
            <img class="shadow" style="border:1px solid black;" src="https://pbs.twimg.com/media/DwFkv2uUcAAZi0O.jpg" width="610" height="610" alt="Body" usemap="#bodymap">

            <map name="bodymap">
                <!--Pink-->

                <area shape="circle" coords="194,90,15" onclick="myFunction('Head')">
                <area shape="circle" coords="413,77,15" onclick="myFunction('Head')">


                <!--Hot Pink-->
                <area shape="rect" coords="151,116,242,141" onclick="myFunction('Neck')">
                <area shape="rect" coords="367,143,460,112" onclick="myFunction('Neck')">

                <!--Orange-->
                <area shape="rect" coords="349,190,478,149" onclick="myFunction('Shoulders')">
                <area shape="rect" coords="129,146,259,188" onclick="myFunction('Chest')">
                <!--Yellow-->
                <area shape="rect" coords="114,318,155,193" onclick="myFunction('Right Arm')">
                <area shape="rect" coords="234,189,274,318" onclick="myFunction('Left Arm')">
                <area shape="rect" coords="333,316,368,189" onclick="myFunction('Left Arm')">
                <area shape="rect" coords="457,206,493,318" onclick="myFunction('Right Arm')">


                <!--Light Green-->
                <area shape="rect" coords="155,191,232,260" onclick="myFunction('Abdomin')">
                <area shape="rect" coords="366,189,453,262" onclick="myFunction('Mid to Lower Back')">

                <!--Green-->
                <area shape="rect" coords="147,314,164,264" onclick="myFunction('Right Hip')">
                <area shape="rect" coords="225,264,241,310" onclick="myFunction('Left Hip')">
                <area shape="rect" coords="368,264,462,330" onclick="myFunction('Behind')">

                <!--Magenta-->
                <area shape="rect" coords="97,318,139,376" onclick="myFunction('Right Hand')">
                <area shape="rect" coords="250,319,292,376" onclick="myFunction('Left Hand')">
                <area shape="rect" coords="312,318,357,377" onclick="myFunction('Left Hand')">
                <area shape="rect" coords="470,322,514,374" onclick="myFunction('Right Hand')">
                <!--Blue-->
                <area shape="rect" coords="143,314,192,552" onclick="myFunction('Right Leg')">
                <area shape="rect" coords="192,552,242,312" onclick="myFunction('Left Leg')">
                <area shape="rect" coords="365,330,414,559" onclick="myFunction('Left Leg')">
                <area shape="rect" coords="414,559,466,333" onclick="myFunction('Right Leg')">

                <!--Purple-->
                <area shape="rect" coords="167,551,240,585" onclick="myFunction('Feet')">
                <area shape="rect" coords="366,558,463,582" onclick="myFunction('Feet')">


            </map>
        </div>
        <div class="col ">
                <div class="card shadow float-right">
                    <div class="card-header">Click the area where the symptom is</div>
                    <div class="card-body">Although multiselect may be coming to soon, we will add one symptom at a time until then.</div>
                </div>
            
        </div>
    </div>
</div>

        <script>
            function myFunction(part) {
                
                var symp = prompt("Are you sure you would like to add a symptom under:", part);
                if (symp == null || symp == "") {
                    window.alert("Must have body part!");
                }
                else {
                    window.location.href = "/Symptom/Index?where=" + part;
                }
            }

        </script>

        

Views/Symptom/Index.cshtml
@model SymTom.ViewModels.AddSymptomViewModel


    <div class="modal-header text-lg-center">
        <h1 class="display-4 ">Add Your Symptom</h1>
    </div>
   

<div class="container">
    <div class="row">
        <div class="col ">
            <form asp-controller="Symptom" asp-action="Add" method="post" >

                <div class="form-group">
                    <label asp-for="Location"></label>
                    <input class="form-control" value='@Context.Request.Query["where"]' asp-for="Location" >
                    <span asp-validation-for="Location"></span>
                </div>


                <div class="form-group">
                    
                    <label asp-for="Name"></label>
                    <input class="form-control " asp-for="Name" placeholder="e.g. Throbbing, Tingling, Burning, etc." />
                    <span asp-validation-for="Name"></span>
                    
                </div>
                <div class="form-group">
                    <label asp-for="Severity"></label>
                   
                    <img style="border-image" src="https://www.disabled-world.com/pics/1/pain-scale-chart-3.gif" alt="Image result for pain chart" width="550"/>
                    <input type="range" class="form-control-range "  min="0" max="10" asp-for="Severity" placeholder="e.g. 1-10" />
                    <span asp-validation-for="Severity"></span>
                    
                </div>


                <div class="form-group">
                    <label asp-for="Date"></label>
                    <input class="form-control " asp-for="Date ">
                    <span asp-validation-for="Date"></span>
                </div>


                <input class="btn btn-primary btn-sm shadow" type="submit" value="Add Symptom" />


            </form>
        </div>
        <div class="col ">
            <div class="card  shadow">
                <div class="card-header shadow">Please help me understand what the symptom is like</div>
                <div class="card-body">-How does it feel?</div>

                <div class="card-body">-Rate your symptom:<br />Left being the least and right being the worst.</div>

                <div class="card-body">-Select the date that you first noticed the symptom.</div>
            </div>
            
        </div>
    </div>
</div>

Views/Symptom/List.cshtml
@model List<SymTom.Models.Symptom>


<div class="modal-header">
    <h1 class="display-2">All of Your Symptoms</h1>
</div>

@if (Model.Count == 0)
{
    <div class="container">
        <div class="col float-left">
            <p>No Symptoms Saved!</p>
        </div>
        <div class="col float-right ">
            <div class="card-deck float-right ">
                <div class="card shadow">
                    <div class="card-header">There are no symptoms in the database</div>
                    <div class="card-body">Please add one to continue.</div>
                </div>
            </div>
        </div>
    </div>
    <p><a class="btn btn-outline-primary btn-sm shadow float-left" asp-controller="Symptom" asp-action="Add">Add Symptom</a></p>

}

@if (Model.Count >= 1)
{
    <div class="container">
        <div class="row">
            <div class="col">
                <table class="table table-bordered  table-striped shadow ">
                    <thead class="thead-dark">
                        <tr>
                            <th>Location</th>
                            <th>Symptom</th>
                            <th>Date</th>
                            <th>Severity</th>
                        </tr>
                    </thead>

                    @foreach (var symptom in Model)
                    {
                        <tr>
                            <td>@symptom.Location</td>
                            <td>@symptom.Name</td>
                            <td>@symptom.Date</td>
                            <td>@symptom.Severity</td>
                        </tr>
                    }
                </table>
            </div>
            <div class="col">
                <iframe class="shadow border-secondary" src="https://healthfinder.gov/myhealthfinder/widget/" name="myhealthfinderframe" frameborder="1" id="myhealthfinderframe" scrolling="yes" height="385" width="100%" marginheight="0" title="myhealthfinder widget" marginwidth="0"></iframe>
            </div>

        </div>
    </div>
 
    <div class="btn-toolbar align-bottom ">

        <p><a class="btn btn-outline-primary btn-sm shadow" asp-controller="Symptom" asp-action="Add">Add Symptom</a>
        <p><a class="btn btn-outline-primary btn-sm shadow" asp-controller="Symptom" asp-action="Remove">Remove Symptom</a>
        <p>
            @using (Html.BeginForm("Index", "CreatePdf"))
            {
                <button class="btn btn-outline-primary btn-sm shadow" id="submitButton" type="submit">Create Pdf</button>

            }
        </p>
    </div>
    
 }

Views/Symptom/Remove.cshtml
@model List<SymTom.Models.Symptom>


<div class="modal-header">
    <h1 class="display-2">Remove Symptom(s)</h1>
</div>
@if (Model.Count == 0)
{  
    <div class="container">
        <div class="col float-left">
            <p>No Symptoms Saved!</p>
        </div>
        <div class="col float-right ">
            <div class="card-deck float-right ">
                <div class="card shadow">
                    <div class="card-header">There are no symptoms in the database</div>
                    <div class="card-body">Please add one to continue.</div>
                </div>
            </div>
        </div>
    </div>
  <p><a class="btn btn-outline-primary btn-sm shadow" asp-controller="Symptom" asp-action="Add">Add Symptom</a></p>

  }

@if (Model.Count >= 1)
{

    <div class="container">
        <div class="col">
            <form method="post" onsubmit="return confirm('Are you sure you want to remove selected symptom(s)?')" class="float-left">
                <table class="table table-bordered  table-striped shadow  ">
                    <thead class="thead-dark">
                        <tr>
                            <th>Selected</th>
                            <th>Location</th>
                            <th>Symptom</th>
                            <th>Date</th>
                            <th>Severity</th>
                        </tr>
                    </thead>
                    @foreach (var symptom in Model)
                    {
                        <tr>
                            <td><input type="checkbox" name="symptomIds" id="@symptom.ID" value="@symptom.ID" /></td>
                            <td>@symptom.Location</td>
                            <td>@symptom.Name</td>
                            <td>@symptom.Date</td>
                            <td>@symptom.Severity</td>
                        </tr>
                    }


                </table>

                <input class="btn btn-outline-primary btn-sm shadow" type="submit" value="Remove Selected Symptom(s)" />
            </form>
        </div>

        <div class="col ">
            <div class="card  shadow float-right">
                <div class="card-header shadow">Select which symptom(s) to remove</div>
                <div class="card-body">-Make sure you've saved them in a pdf first!</div>


            </div>

        </div>
    </div>


}